---
title: "Cross Validation"
author: "Weida Gong"
date: "June 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cross Validation

```{r cars}
load('tissuesGeneExpression.rda')
```

Drop tissue with low sample numbers

```{r}
table(tissue)

index <- which(tissue != 'placenta')
y <- tissue[index]
x <- t(e[, index])
```
## KNN classification

```{r}
library(class)
pred <- knn(train = x, test = x, cl = y, k = 5)
mean(y!= pred)

```
## Cross Validation
```{r}
library(caret)
set.seed(1)
idx <- createFolds(y, k = 10)
sapply(idx, length)
```
Only use two dimensional data for computational purposes

```{r}
pca <- prcomp(x, scale. = F, center = F)
x1 <- pca$x[,1]
x2 <- pca$x[,2]
plot(x1, x2, col = as.numeric(factor(y)))
```
Error rate with 1st fold out
```{r}
xsmall <- pca$x[, 1:5]
pred <- knn(train = xsmall[-idx[[1]], ], test = xsmall[idx[[1]], ], cl = y[-idx[[1]]], k = 5)
table(true = y[idx[[1]]], pred)
```

```{r}
mean(y[idx[[1]]] != pred)
```


Try for the other folds
```{r}
for (i in 1:10){
  pred <- knn(train = xsmall[-idx[[i]], ], test = xsmall[idx[[i]],], cl = y[-idx[[i]]], k = 5)
  print(paste(i, ":Error rate : ", round(mean(y[idx[[i]]] != pred), 3), sep = ""))
}
```

Try for other ks

```{r}
set.seed(1)
ks <- 1:12

res <- sapply(ks, function(k){
  subres <- sapply(seq_along(idx), function(i){
    pred <- knn(train = xsmall[-idx[[i]], ], test = xsmall[idx[[i]], ],
                cl = y[-idx[[i]]], k = k)
    return(mean(y[idx[[i]]] != pred))
  })
  return(mean(subres))
}) 

plot(ks, res, type = "o", ylim = c(0, 0.3), ylab = "Error rate")
```