---
title: "Moderated t-tests"
author: "Weida Gong"
date: "June 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Simple t-tests


```{r include=FALSE}
library(SpikeInSubset)
data(rma95)
fac <- factor(rep(1:2, each = 3))
pData(rma95)
```
The first trio and second trio samples should have fixed spike in. But considerable variability is detected.

```{r}
par(mfrow = c(2,2))
for (i in 1:4) {
  spg <- names(pData(rma95))
  plot(1:6, exprs(rma95)[spg[i+6], ], main = spg[i+6], ylab = "RMA", xlab = "Spike-in",
       axes = F)
  axis(2)
  axis(1, at = 1:6, labels = pData(rma95)[, spg[i + 6]])
}
```

## rowttests

```{r}
library(genefilter)

rtt <- rowttests(exprs(rma95), fac)
mask <- with(rtt, abs(dm) < 0.2 & p.value < 0.01)
spike <- rownames(rma95) %in% colnames(pData(rma95))
cols <- ifelse(mask, "red", ifelse(spike, "dodgerblue", "black"))
```

Red dots were False Positive that were not supposed to be DE
```{r}
plot(-rtt$dm, -log10(rtt$p.value), pch=16, xlim = c(-1, 1),
     ylim = c(0, 5), xlab = "difference in means", col = cols)
abline(h = 2, v = c(-0.2, 0.2), lty = 2)

```

Red dots have really low variance
```{r}
rtt$s <- apply(exprs(rma95), 1, function(row){
  return(sqrt(0.5 * (var(row[1:3]) + var(row[4:6]))))
})

plot(rtt$s, -log10(rtt$p.value), pch = 16, log = "x", xlab = "Log SD", col= cols)
```

## Use limma to correct for variance

```{r}
library(limma)
options(digits = 3)

fit <- lmFit(rma95, design = model.matrix(~fac)) #step 1 least squares estimates
fit <- eBayes(fit) # step 2 moderate the t statistics
tt <- topTable(fit, coef = 2, number = Inf, sort.by = "none")
limmares <- data.frame(dm = coef(fit)[, "fac2"], p.value = fit$p.value[, "fac2"])

plot(limmares$dm, -log10(limmares$p.value), pch = 16, col = cols, xlab = "difference in means",
     xlim = c(-1, 1), ylim = c(0, 5))

abline(h =2, v = c(-0.2, 0.2), lty = 2)
```
Tha variance is now corrected

```{r}
n = 40
qs <- seq(0, 0.2, length = n)
idx <- sapply(1:n, function(i) which(as.integer(cut(rtt$s^2, qs)) == i)[1])
idx <- idx[!is.na(idx)]

plot(1, 1, xlim = c(0, 0.2), ylim = c(0, 1), type = "n",
     xlab = "variance estimates", ylab = "", yaxt = "n")
axis(2, at = c(0.1, 0.9), c("before", "after"))
segments((rtt$s^2)[idx], rep(0.1, n), fit$s2.post[idx], rep(0.9, n))
```
